#!/usr/bin/env python3
"""Generate bash, zsh and fish completion files from agent_toggle.cli.build_parser().

    python3 tools/gen_completions.py [outdir]     # default: completions/

Static files, no runtime dependency; run at release time (see release.yml).
Source of truth is the argparse parser, so a new command or flag shows up on
the next release without touching this file.
"""
from __future__ import annotations

import argparse
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from agent_toggle.cli import build_parser  # noqa: E402

PROG = "agent-toggle"


def _opts(p: argparse.ArgumentParser) -> list[argparse.Action]:
    return [a for a in p._actions
            if a.option_strings and not isinstance(a, argparse._HelpAction)]


def _model(parser: argparse.ArgumentParser):
    """(global option actions, {command: (help, subparser)}); aliases are commands too."""
    sub = next(a for a in parser._actions if isinstance(a, argparse._SubParsersAction))
    helps = {ca.dest: ca.help or "" for ca in sub._choices_actions}
    cmds = {}
    for name, p in sub.choices.items():
        h = helps.get(name) or next((helps[n] for n, q in sub.choices.items()
                                     if q is p and n in helps), "")
        cmds[name] = (h, p)
    return _opts(parser), cmds


def _flags(a: argparse.Action) -> list[str]:
    """Option strings of one action, long form first."""
    return sorted(a.option_strings, key=lambda s: (not s.startswith("--"), s))


def _takes_value(a: argparse.Action) -> bool:
    return a.nargs != 0


def bash(parser: argparse.ArgumentParser) -> str:
    glob, cmds = _model(parser)
    value_choices: dict[str, list[str]] = {}
    per_cmd = {}
    for name, (_, p) in cmds.items():
        words: list[str] = []
        for a in p._actions:
            if a.option_strings and not isinstance(a, argparse._HelpAction):
                words += a.option_strings
            elif a.choices:
                words += list(a.choices)
        per_cmd[name] = words
    for a in glob + [a for _, p in cmds.values() for a in _opts(p)]:
        if a.choices:
            for f in a.option_strings:
                value_choices[f] = list(a.choices)
    gwords = [f for a in glob for f in a.option_strings]
    lines = [f"# bash completion for {PROG}; generated by tools/gen_completions.py",
             "_agent_toggle() {",
             "  local cur prev cmd w",
             '  cur="${COMP_WORDS[COMP_CWORD]}"; prev="${COMP_WORDS[COMP_CWORD-1]}"',
             '  case "$prev" in']
    for f, ch in sorted(value_choices.items()):
        lines.append(f'    {f}) COMPREPLY=($(compgen -W "{" ".join(ch)}" -- "$cur")); return ;;')
    lines += ["  esac",
              '  for w in "${COMP_WORDS[@]:1:COMP_CWORD-1}"; do',
              '    case "$w" in',
              f"      {'|'.join(cmds)}) cmd=$w; break ;;",
              "    esac",
              "  done",
              '  case "$cmd" in']
    for name, words in per_cmd.items():
        lines.append(f'    {name}) COMPREPLY=($(compgen -W "{" ".join(words)}" -- "$cur")) ;;')
    lines += [f'    *) COMPREPLY=($(compgen -W "{" ".join(cmds)} {" ".join(gwords)}" -- "$cur")) ;;',
              "  esac", "}",
              f"complete -F _agent_toggle {PROG}", ""]
    return "\n".join(lines)


def _zq(s: str) -> str:
    """Escape a help string for a zsh single-quoted _arguments spec."""
    return s.replace("'", "'\\''").replace("[", "(").replace("]", ")").replace(":", " -")


def _zspec(a: argparse.Action) -> list[str]:
    out = []
    for f in _flags(a):
        spec = f"{f}[{_zq(a.help or '')}]"
        if _takes_value(a):
            name = str(a.metavar or a.dest).lower()
            spec += f":{name}:" + (f"({' '.join(a.choices)})" if a.choices else "_files")
        out.append(f"'{spec}'")
    return out


def _zpos(a: argparse.Action, i: int) -> str:
    name = str(a.metavar or a.dest).lower()
    comp = f"({' '.join(a.choices)})" if a.choices else ""
    if a.nargs in ("*", "+"):
        return f"'*:{name}:{comp}'"
    return f"'{i}{':' if a.nargs == '?' else ''}:{name}:{comp}'"


def zsh(parser: argparse.ArgumentParser) -> str:
    glob, cmds = _model(parser)
    lines = [f"#compdef {PROG}",
             f"# zsh completion for {PROG}; generated by tools/gen_completions.py",
             "_agent_toggle() {", "  local -a commands", "  commands=("]
    lines += [f"    '{n}:{_zq(h)}'" for n, (h, _) in cmds.items()]
    lines += ["  )", '  local curcontext="$curcontext" state line', "  typeset -A opt_args",
              "  _arguments -C \\"]
    lines += [f"    {s} \\" for a in glob for s in _zspec(a)]
    lines += ["    '1: :->cmd' \\", "    '*:: :->args'",
              "  case $state in", "    cmd) _describe -t commands command commands ;;",
              "    args)", "      case $line[1] in"]
    for name, (_, p) in cmds.items():
        specs = [s for a in _opts(p) for s in _zspec(a)]
        pos = [a for a in p._actions if not a.option_strings]
        specs += [_zpos(a, i) for i, a in enumerate(pos, 1)]
        lines.append(f"        {name}) _arguments {' '.join(specs) or ':'} ;;")
    lines += ["      esac ;;", "  esac", "}", '_agent_toggle "$@"', ""]
    return "\n".join(lines)


def _fq(s: str) -> str:
    return "'" + s.replace("\\", "\\\\").replace("'", "\\'") + "'"


def _fish_flag(a: argparse.Action, cond: str | None) -> str:
    parts = [f"complete -c {PROG}"]
    if cond:
        parts.append(f"-n {_fq(cond)}")
    for f in _flags(a):
        parts.append(f"-l {f[2:]}" if f.startswith("--") else f"-s {f[1:]}")
    if _takes_value(a):
        parts.append("-x" + (f" -a {_fq(' '.join(a.choices))}" if a.choices else " -r"))
    parts.append(f"-d {_fq(a.help or '')}")
    return " ".join(parts)


def fish(parser: argparse.ArgumentParser) -> str:
    glob, cmds = _model(parser)
    lines = [f"# fish completion for {PROG}; generated by tools/gen_completions.py",
             f"complete -c {PROG} -f"]
    for n, (h, _) in cmds.items():
        lines.append(f"complete -c {PROG} -n __fish_use_subcommand -a {n} -d {_fq(h)}")
    lines += [_fish_flag(a, None) for a in glob]
    for n, (_, p) in cmds.items():
        cond = f"__fish_seen_subcommand_from {n}"
        lines += [_fish_flag(a, cond) for a in _opts(p)]
        for a in p._actions:
            if not a.option_strings and a.choices:
                lines.append(f"complete -c {PROG} -n {_fq(cond)} -a {_fq(' '.join(a.choices))}")
    lines.append("")
    return "\n".join(lines)


def generate() -> dict[str, str]:
    """{filename: content} for every shell."""
    p = build_parser()
    return {f"{PROG}.bash": bash(p), f"_{PROG}": zsh(p), f"{PROG}.fish": fish(p)}


def main(argv: list[str]) -> int:
    out = Path(argv[0] if argv else "completions")
    out.mkdir(parents=True, exist_ok=True)
    for name, text in generate().items():
        (out / name).write_text(text, encoding="utf-8")
        print(out / name)
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
